### ISSUE TITLE
nng compatibility

### ISSUE THREAD

**Issue by afshin2003** [void-dragon/nanomsg-browser#4]
Hi,
Have you ever tested it with nng version? As stated in the documentation, nng is wire compatible with nanomsg. I am just curious about using Connect method instead of Dial to connect to a nng socket.

Afshin

**Comment by void-dragon** [comment]
No i never tested this myself.
But if you do i would be glad to here what you find out.

**Comment by TojikCZ** [comment]
It seems to work with nng using publish subscribe just fine

**Comment by void-dragon** [comment]
i can confirm that NNG works, BUT there are some little things, like nanomsg supported string messages aswell, NNG only takes ArrayBuffer.

But since i could confirm that it works, i will close this ticket now.
