### ISSUE TITLE
Cannot send

### ISSUE THREAD

**Issue by TojikCZ** [void-dragon/nanomsg-browser#6]
Hi, I encountered a bug when trying to send a message using the PAIR socket. The websocket closed for no apparent reason. Later i discovered that when it closes the event carries an error code, which gave me 1003. Which according to https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent means unsupported data. Please log it in the debug mode. It's too useful to be ignored.

The solution was to convert the string manually to something the websocket supports like an ArrayBuffer. I got this working with the nng pair example code available here: https://nanomsg.org/gettingstarted/nng/pair.html

I debugged your code on Repl.it, so I can give you the link to a working example: https://repl.it/repls/StrongExternalFan

Anyway, thank you very much for publishing your code. It saved me loads of time regardless of this bug.

As a bonus, your code seems to be compatible with NNG. Hurray :partying_face:

**Comment by void-dragon** [comment]
I am absolutely baffled that someone uses this package at all.
But it seems i need to detect better if i get some binary or string data.

**Comment by TojikCZ** [comment]
Also, I tried adding the bus protocol (guessed the websocket string thingy) and it works. My app can now talk to multiple web clients and receive their messages.

**Comment by void-dragon** [comment]
I did add better string encoding via the TextEncoder object.
If you look in the dev branch you can see and test it if you like.

**Comment by TojikCZ** [comment]
Everything you changed regarding the encoding of a message looks to be enclosed in 
`if (this.protocol === nanomsg.REQ)`
preventing it to have any effect when not using REQ
I am using BUS: `BUS: 'bus.sp.nanomsg.org',`
don't feel obligated to change stuff, I already have a working version ;) and will not be able to test everything as I am using this for work. Which is new for me :D

**Comment by darorl89** [comment]
@void-dragon I'm using it aswell, don't be baffled, it's the only browser connector available.
@TojikCZ could you share your solution?

**Comment by void-dragon** [comment]
i implemented the BUS support in version 0.2, so thats why i am closing this ticket now :)
