### ISSUE TITLE
Configuration and modules

### ISSUE THREAD

**Issue by dehorsley** [void-dragon/nanomsg-browser#7]
Setting the package wide configuration variables have no effect when used with modules. For example, the following:

```js
import nanomsg from 'nanomsg-browser';
nanomsg.receiveArrayBuffer = true;
nanomsg.debug = true;

const sub = new nanomsg.Socket(nanomsg.SUB);
sub.connect(subaddr);
sub.on('data',  (msg) => {
    console.log(typeof msg);
});

```

logs `"string"`, while I would expect an Array Buffer.

I believe the problem is here:

```js
if (typeof exports !== 'undefined') {
  Object.assign(exports, nanomsg);
}
```

Which means `exports` is now a copy of the `nanomsg` object, not a reference, and changes to it are not reflected in the object the `Socket` methods see. Keeping the CommonJS syntax, you can instead do:

```js
if (typeof module !== 'undefined') {
  module.exports = nanomsg;
}
```

I'm not sure how this will work with other systems such as ES6 modules, but I suspect that will properly will probably require something different. Adding getters and setters might be a solution.

**Comment by void-dragon** [comment]
As i have already written in the comment to the pull request.
I have changed the source code structure for version 0.2.0.
But thank you for the effort.

The new version should work now with WebPack and Browserify.
